proxy:
  port: 8080
  container-wait-time: 30000
  authentication: simple
  admin-groups: admins
  users:
  - name: cedunia
    password: cedunia
    groups: admins
  - name: user1
    password: user1_pass
  - name: user2
    password: user2_pass
  - name: user3
    password: user3_pass
  docker:
      internal-networking: true
  specs:
  - id: edaoniris
    description: Déploiement de ma première application shiny
    container-cmd: ["R", "-e", "EDAOnIris::shiny_application()"]
    container-image: cedunia/edaoniris
    container-network: sp-example-net
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
logging:
  file:
    shinyproxy.log
