proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: cedunia
    password: cedunia
    groups: admins
  - name: user1
    password: user1_pass
  docker:
      internal-networking: true
  specs:
  - id: edaoniris
    display-name: EDA on Iris dataset
    description: First Shiny Application deployed with Shiny Proxy
    container-cmd: ["R", "-e", "EDAOnIris::shiny_application()"]
    container-image: cedunia/edaoniris
    container-network: sp-example-net
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log